import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

const createArtistStyles = StyleSheet.create({
    screen: {
        flex: 1,
        backgroundColor: '#fff',
    },
    headerContainer: {
        paddingTop: 40,
        backgroundColor: '#fff',
        borderBottomWidth: 1,
        borderBottomColor: '#F3F4F6',
    },
    navRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: 16,
        marginBottom: 20,
        height: 48,
    },
    backButtonPlaceholder: {
        width: 50,
        height: 50,
    },
    backButton: {
        width: 50,
        height: 50,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#F3ECFF',
        borderRadius: 15,
        marginRight: 12,
    },
    headerTitle: {
        fontSize: 24,
        fontWeight: '700',
        color: '#7C3AED',
    },
    tabsRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingBottom: 10,
    },
    tabItem: {
        flex: 1,
        alignItems: 'center',
    },
    tabText: {
        width: '33.33%',
        marginTop: 10,
        textAlign: 'center',
        fontSize: 13,
        fontWeight: '500',
        color: '#6B7280',
    },
    activeTabText: {
        color: '#111827',
        fontWeight: '600',
    },
    progressBarTrack: {
        height: 4,
        backgroundColor: '#E5E7EB',
        width: '100%',
        flexDirection: 'row',
    },
    progressBarFill: {
        height: '100%',
        backgroundColor: '#7C3AED',
        borderTopRightRadius: 4,
        borderBottomRightRadius: 4,
    },
    scrollContent: {
        padding: 16,
    },
    sectionHeader: {
        fontSize: 20,
        fontWeight: '500',
        color: '#111827',
        marginTop: 20,
        marginBottom: 30,
    },

    // Upload Box
    uploadBox: {
        borderWidth: 1.5,
        borderColor: '#D1D5DB',
        borderRadius: 12,
        borderStyle: 'dashed',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 30,
        marginBottom: 20,
        backgroundColor: '#F9FAFB',
    },
    uploadIconCircle: {
        width: 48,
        height: 48,
        borderRadius: 24,
        backgroundColor: '#F3ECFF',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 10,
    },
    uploadTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: '#111827',
        marginBottom: 10,
    },
    uploadSubtitle: {
        fontSize: 14,
        color: '#6B7280',
        marginTop: 4,
    },

    fieldLabel: {
        fontSize: 15,
        fontWeight: '500',
        color: '#374151',
        marginBottom: 18,
    },

    // Button
    saveButton: {
        backgroundColor: '#7C3AED',
        height: 54,
        borderRadius: 12,
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 20,
        shadowColor: '#7C3AED',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 8,
        elevation: 4,
    },
    saveButtonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '600',
    },
    radiusInfoRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: -8,
        marginBottom: 20,
    },
    radiusValueText: {
        fontSize: 14,
        fontWeight: '600',
        color: '#111827',
    },
    radiusHelperText: {
        fontSize: 16,
        color: '#6B7281',
        flex: 1,
        textAlign: 'right',
    },
    helperText: {
        fontSize: 14,
        color: '#6B7280',
        marginBottom: 30,
    },
    sectionTitle: {
        fontSize: 16,
        fontWeight: '500',
        color: '#374151',
    },
    imageGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 12,
    },
    gridImage: {
        width: '100%',
        height: '100%',
        borderRadius: 12,
        backgroundColor: '#F3F4F6',
    },
    gridImageWrapper: {
        width: (width - 32 - 24) / 3,
        height: (width - 32 - 24) / 3,
        marginBottom: 12,
        position: 'relative',
    },
    subSectionTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: '#111827',
        marginBottom: 4,
    },
    subSectionHelper: {
        fontSize: 13,
        color: '#6B7280',
        marginBottom: 16,
    },
    primaryImagesList: {
        marginBottom: 10,
    },
    primaryImageWrapper: {
        marginBottom: 16,
        position: 'relative',
    },
    primaryImageItem: {
        width: '100%',
        height: 180,
        borderRadius: 12,
        backgroundColor: '#F3F4F6',
    },
    removeBtn: {
        position: 'absolute',
        top: 10,
        right: 10,
        backgroundColor: 'rgba(0,0,0,0.6)',
        width: 28,
        height: 28,
        borderRadius: 14,
        justifyContent: 'center',
        alignItems: 'center',
    },
    removeBtnSmall: {
        position: 'absolute',
        top: 6,
        right: 6,
        backgroundColor: 'rgba(0,0,0,0.6)',
        width: 24,
        height: 24,
        borderRadius: 12,
        justifyContent: 'center',
        alignItems: 'center',
    },

    // Service Step
    serviceImagesRow: {
        flexDirection: 'row',
        gap: 12,
        paddingBottom: 8,
    },
    serviceImageItem: {
        width: 80,
        height: 80,
        borderRadius: 12,
        backgroundColor: '#F3F4F6',
        marginRight: 10,
    },
    addServiceHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginTop: 20,
        marginBottom: 20,
    },
    addServiceBtn: {
        width: 36,
        height: 36,
        borderRadius: 8,
        backgroundColor: '#F3ECFF',
        justifyContent: 'center',
        alignItems: 'center',
    },
    serviceCard: {
        borderWidth: 1,
        borderColor: '#E5E7EB',
        borderRadius: 16,
        padding: 16,
        marginBottom: 20,
    },
    serviceHeaderRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 10,
    },
    serviceTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: '#111827',
    },
    serviceBody: {
        marginTop: 10,
    },
    rowInputs: {
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    halfInput: {
        width: '48%',
    },
    procedureButton: {
        borderWidth: 1,
        borderColor: '#C4B5FD',
        backgroundColor: '#F3ECFF',
        borderRadius: 12,
        height: 50,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 24,
    },
    procedureBtnText: {
        color: '#7C3AED',
        fontWeight: '600',
        fontSize: 16,
    },
    extraInfoBox: {
        backgroundColor: '#F3ECFF',
        borderRadius: 16,
        padding: 16,
        borderWidth: 1,
        borderColor: '#E9D5FF',
    },
    extraInfoHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 16,
    },
    extraInfoTitle: {
        fontSize: 15,
        fontWeight: '600',
        color: '#1F2937',
        flex: 1,
        paddingRight: 10,
    },
    smallLabel: {
        fontSize: 13,
        color: '#4B5563',
        marginBottom: 8,
        marginTop: 4,
    },
    textArea: {
        backgroundColor: '#fff',
        borderRadius: 12,
        padding: 12,
        height: 100,
        color: '#1F2937',
        marginBottom: 16,
        borderWidth: 1,
        borderColor: '#E5E7EB',
    },
    sectionHeaderNoMargin: {
        fontSize: 20,
        fontWeight: '500',
        color: '#111827',
    },

    // Procedure Summary Box
    procedureSummaryBox: {
        borderWidth: 1,
        borderColor: '#E5E7EB',
        borderRadius: 12,
        padding: 16,
        marginBottom: 24,
        backgroundColor: '#fff',
    },
    procedureSummaryItem: {
        flexDirection: 'row',
        marginBottom: 16,
        borderBottomWidth: 1,
        borderBottomColor: '#F3F4F6',
        paddingBottom: 12,
    },
    procIndex: {
        fontSize: 16,
        fontWeight: '600',
        color: '#111827',
        marginRight: 12,
        width: 20,
    },
    procTitle: {
        fontSize: 15,
        fontWeight: '600',
        color: '#111827',
        marginBottom: 4,
    },
    procDesc: {
        fontSize: 13,
        color: '#6B7280',
    },
    editProcedureBtn: {
        backgroundColor: '#F3ECFF',
        borderRadius: 10,
        height: 48,
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#C4B5FD',
    },
    editProcedureText: {
        color: '#7C3AED',
        fontSize: 15,
        fontWeight: '600',
    },

    // Exclusive Essentials
    essentialsSection: {
        marginTop: 20,
        marginBottom: 8,
    },
    essentialsSectionHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        marginBottom: 14,
    },
    essentialsAddBtn: {
        width: 34,
        height: 34,
        borderRadius: 8,
        backgroundColor: '#F3ECFF',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#C4B5FD',
        marginTop: 2,
    },
    essentialsEmptyBox: {
        borderWidth: 1.5,
        borderColor: '#D1D5DB',
        borderStyle: 'dashed',
        borderRadius: 14,
        alignItems: 'center',
        paddingVertical: 28,
        backgroundColor: '#F9FAFB',
        marginBottom: 8,
    },
    essentialsEmptyIcon: {
        width: 52,
        height: 52,
        borderRadius: 26,
        backgroundColor: '#F3ECFF',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 10,
    },
    essentialsEmptyTitle: {
        fontSize: 15,
        fontWeight: '600',
        color: '#111827',
        marginBottom: 4,
    },
    essentialsEmptySubtitle: {
        fontSize: 13,
        color: '#6B7280',
        textAlign: 'center',
        paddingHorizontal: 24,
    },
    essentialsGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 10,
    },
    essentialCard: {
        width: (width - 32 - 10) / 2,
        borderRadius: 14,
        backgroundColor: '#fff',
        borderWidth: 1,
        borderColor: '#E5E7EB',
        overflow: 'hidden',
        marginBottom: 2,
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.06,
        shadowRadius: 4,
        position: 'relative',
    },
    essentialCardImage: {
        width: '100%',
        height: 110,
        backgroundColor: '#F3F4F6',
    },
    essentialCardTitle: {
        fontSize: 13,
        fontWeight: '600',
        color: '#111827',
        padding: 10,
        paddingTop: 8,
    },
    essentialRemoveBtn: {
        position: 'absolute',
        top: 7,
        right: 7,
        backgroundColor: 'rgba(0,0,0,0.55)',
        width: 22,
        height: 22,
        borderRadius: 11,
        justifyContent: 'center',
        alignItems: 'center',
    },
    essentialAddTile: {
        width: (width - 32 - 10) / 2,
        height: 145,
        borderRadius: 14,
        borderWidth: 1.5,
        borderStyle: 'dashed',
        borderColor: '#C4B5FD',
        backgroundColor: '#F9F5FF',
        justifyContent: 'center',
        alignItems: 'center',
        gap: 6,
    },
    essentialAddTileText: {
        fontSize: 13,
        color: '#7C3AED',
        fontWeight: '500',
    },

    // Essential Modal
    essentialModalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.45)',
        justifyContent: 'flex-end',
    },
    essentialModalSheet: {
        backgroundColor: '#fff',
        borderTopLeftRadius: 24,
        borderTopRightRadius: 24,
        padding: 24,
        paddingBottom: 36,
    },
    essentialModalHandle: {
        width: 40,
        height: 4,
        borderRadius: 2,
        backgroundColor: '#D1D5DB',
        alignSelf: 'center',
        marginBottom: 20,
    },
    essentialModalTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: '#111827',
        marginBottom: 4,
    },
    essentialModalSubtitle: {
        fontSize: 13,
        color: '#6B7280',
        marginBottom: 20,
    },
    essentialImagePickerBox: {
        borderWidth: 1.5,
        borderColor: '#D1D5DB',
        borderStyle: 'dashed',
        borderRadius: 14,
        alignItems: 'center',
        paddingVertical: 22,
        marginBottom: 20,
        backgroundColor: '#F9FAFB',
    },
    essentialImagePickerIcon: {
        width: 50,
        height: 50,
        borderRadius: 25,
        backgroundColor: '#F3ECFF',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 8,
    },
    essentialImagePickerText: {
        fontSize: 14,
        fontWeight: '600',
        color: '#374151',
        marginBottom: 3,
    },
    essentialImagePickerSub: {
        fontSize: 12,
        color: '#9CA3AF',
    },
    essentialInputLabel: {
        fontSize: 14,
        fontWeight: '500',
        color: '#374151',
        marginBottom: 8,
    },
    essentialInput: {
        borderWidth: 1,
        borderColor: '#E5E7EB',
        borderRadius: 12,
        paddingHorizontal: 14,
        paddingVertical: 12,
        fontSize: 14,
        color: '#111827',
        backgroundColor: '#F9FAFB',
        marginBottom: 24,
    },
    essentialModalActions: {
        flexDirection: 'row',
        gap: 12,
    },
    essentialCancelBtn: {
        flex: 1,
        height: 48,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#E5E7EB',
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#F9FAFB',
    },
    essentialCancelText: {
        color: '#6B7280',
        fontWeight: '600',
        fontSize: 15,
    },
    essentialConfirmBtn: {
        flex: 1.6,
        height: 48,
        borderRadius: 12,
        backgroundColor: '#7C3AED',
        justifyContent: 'center',
        alignItems: 'center',
        elevation: 2,
    },
    essentialConfirmText: {
        color: '#fff',
        fontWeight: '700',
        fontSize: 15,
    },

    // Map Location Picker
    mapLoadingBox: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#F3F0FF',
        borderRadius: 12,
        padding: 14,
        marginTop: 8,
        marginBottom: 4,
        gap: 10,
    },
    mapLoadingText: {
        color: '#7C3AED',
        fontSize: 14,
        fontWeight: '500',
    },
    mapContainer: {
        marginTop: 10,
        marginBottom: 6,
        borderRadius: 16,
        overflow: 'hidden',
        borderWidth: 1.5,
        borderColor: '#DDD6FE',
        backgroundColor: '#fff',
    },
    mapHeaderRow: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 14,
        paddingTop: 14,
        paddingBottom: 4,
    },
    mapLabel: {
        fontSize: 15,
        fontWeight: '600',
        color: '#374151',
    },
    mapAddressText: {
        fontSize: 12,
        color: '#6B7280',
        marginHorizontal: 14,
        marginBottom: 2,
    },
    mapHintText: {
        fontSize: 12,
        color: '#9CA3AF',
        marginHorizontal: 14,
        marginBottom: 10,
        fontStyle: 'italic',
    },
    map: {
        width: '100%',
        height: 220,
    },
    mapCoordsRow: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 14,
        paddingVertical: 10,
        backgroundColor: '#F9FAFB',
    },
    mapCoordsText: {
        fontSize: 12,
        color: '#6B7280',
        fontFamily: 'monospace' as any,
    },
    mapImageWrapper: {
        position: 'relative',
        borderRadius: 12,
        overflow: 'hidden',
        marginBottom: 0,
    },
    mapRefreshBadge: {
        position: 'absolute',
        bottom: 8,
        right: 8,
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(124,58,237,0.85)',
        borderRadius: 20,
        paddingHorizontal: 10,
        paddingVertical: 5,
    },
    mapRefreshText: {
        color: '#fff',
        fontSize: 11,
        fontWeight: '600',
    },

    // KYC Document styles
    kycCard: {
        backgroundColor: '#fff',
        borderRadius: 16,
        padding: 16,
        marginTop: 16,
        borderWidth: 1,
        borderColor: '#EDE9FE',
        elevation: 2,
    },
    kycCardHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 14,
        gap: 12,
    },
    kycIconBadge: {
        width: 40,
        height: 40,
        borderRadius: 12,
        backgroundColor: '#F3F0FF',
        justifyContent: 'center',
        alignItems: 'center',
    },
    kycCardTitle: {
        fontSize: 15,
        fontWeight: '600',
        color: '#111827',
    },
    kycCardSub: {
        fontSize: 12,
        color: '#9CA3AF',
        marginTop: 2,
    },
    kycDoneBadge: {
        width: 24,
        height: 24,
        borderRadius: 12,
        backgroundColor: '#10B981',
        justifyContent: 'center',
        alignItems: 'center',
    },
    kycImagesRow: {
        flexDirection: 'row',
        gap: 12,
        marginTop: 4,
    },
    kycImageSlot: {
        flex: 1,
    },
    kycSlotLabel: {
        fontSize: 12,
        color: '#6B7280',
        fontWeight: '500',
        marginBottom: 6,
    },
    kycPreviewWrapper: {
        position: 'relative',
        borderRadius: 10,
        overflow: 'hidden',
    },
    kycPreview: {
        width: '100%',
        height: 110,
        borderRadius: 10,
    },
    kycRemoveBtn: {
        position: 'absolute',
        top: 6,
        right: 6,
        width: 22,
        height: 22,
        borderRadius: 11,
        backgroundColor: 'rgba(239,68,68,0.9)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    kycUploadBox: {
        height: 110,
        borderRadius: 10,
        borderWidth: 1.5,
        borderColor: '#DDD6FE',
        borderStyle: 'dashed',
        backgroundColor: '#FAFAFF',
        justifyContent: 'center',
        alignItems: 'center',
        gap: 6,
    },
    kycUploadText: {
        fontSize: 12,
        color: '#7C3AED',
        fontWeight: '600',
        marginTop: 4,
    },
});

export default createArtistStyles;
